# Generated by Django 5.0.1 on 2024-01-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.FloatField(null=True),
        ),
    ]
